apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'administration'
        scheme: http
        metrics_path: 'metrics'
        static_configs:
        - targets: ['{{ .Release.Name }}-administration']
      - job_name: 'authserver'
        scheme: http
        metrics_path: 'metrics'
        static_configs:
        - targets: ['{{ .Release.Name }}-authserver']
      - job_name: 'identity'
        scheme: http
        metrics_path: 'metrics'
        static_configs:
        - targets: ['{{ .Release.Name }}-identity']
      - job_name: 'web'
        scheme: http
        metrics_path: 'metrics'
        static_configs:
        - targets: ['{{ .Release.Name }}-web']