apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  serviceName: "{{ .Release.Name }}-{{ .Chart.Name }}"
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-{{ .Chart.Name }}"
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: "{{ .Release.Name }}-{{ .Chart.Name }}"
          ports:
            - name: "{{ .Chart.Name }}"
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
              readOnly: true
      volumes:
        - name: prometheus-config
          configMap:
            name: "{{ .Release.Name }}-{{ .Chart.Name }}"