apiVersion: v1
kind: Service
metadata:
  labels:
    name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
spec:
  type: ClusterIP
  ports:
    - name: "http"
      protocol: TCP
      port: {{ .Values.ports.http }}
      targetPort: {{ .Values.ports.http }}
    - name: "amqp"
      protocol: TCP
      port: {{ .Values.ports.amqp }}
      targetPort: {{ .Values.ports.amqp }}
  selector:
    app: "{{ .Release.Name }}-{{ .Chart.Name }}"

